### ISSUE TITLE
IMGS is undefined with remote images on iOS

### ISSUE THREAD

**Issue by Topener** [apra-informatica/Ti.ImageViewer#5]
When downloading (bigger) images remotely, it triggers this error when I try to resize it. Clicking the image (to reset scaling) fixes it.

Doesn't happen when image is already cached and loaded

Only happens with remote images on iOS (as Android doesn't support remote images, I cannot test it)

``````
[ERROR] :  Script Error {
[ERROR] :      column = 24;
[ERROR] :      line = 154;
[ERROR] :      message = "undefined is not an object (evaluating 'IMGS.width')";
[ERROR] :      sourceURL = "file:///Users/renepot/Library/Developer/CoreSimulator/Devices/C02E83ED-17DA-4244-923C-C90923CBBA09/data/Containers/Bundle/Application/DA8A3624-6ACF-44E1-BF15-2D895D04AA79/Roamler.app/alloy/widgets/it.apra.tiimageviewer/controllers/widget.js";
[ERROR] :      stack = "getMaxOffset@file:///Users/renepot/Library/Developer/CoreSimulator/Devices/C02E83ED-17DA-4244-923C-C90923CBBA09/data/Containers/Bundle/Application/DA8A3624-6ACF-44E1-BF15-2D895D04AA79/Roamler.app/alloy/widgets/it.apra.tiimageviewer/controllers/widget.js:154:24\nfile:///Users/renepot/Library/Developer/CoreSimulator/Devices/C02E83ED-17DA-4244-923C-C90923CBBA09/data/Containers/Bundle/Application/DA8A3624-6ACF-44E1-BF15-2D895D04AA79/Roamler.app/alloy/widgets/it.apra.tiimageviewer/controllers/widget.js:219:86";
[ERROR] :  }```
``````

**Comment by nonno** [comment]
Sorry but I never checked with remote images, example in the readme was added by another person now I removed it. The module used in Android doesn't work with remote images so it doesn't have sense to support it only on iOS (and I don't need it).
By the way I tried to use "http://www.google.com/images/srpr/logo11w.png" on an iPad and a iPhone 4s too, I cannot reproduce this problem, apparently the resize works.

**Comment by nilokadnedzar** [comment]
The problem is still present. I just check it with Ti 5.5.1 and iOS 10 Simulator. The Image appears but when start scrolling the error occurs.

<img width="323" alt="bildschirmfoto 2016-10-28 um 12 44 23" src="https://cloud.githubusercontent.com/assets/966334/19805613/e2109514-9d15-11e6-8934-833b30288d0b.png">

PS: I discovered that when you place a label with a click-event into the same window (e.g. let the label fire an alert) and confirming it the window gets refreshed and your idgets works just fine.
I think some timeouts or some checking if the image is already there is missing in the widget logic.

Another discovery on the real device: The image is zoomed-in at first (when the window with the widget is opened). When you tap the image once it gets resized into a fit-to-screen size and the Widget works.

**Comment by nonno** [comment]
Hi Niels, in next days I won't have time and the project where I used this widget is close to his end. Maybe one day I'll try again to reproduce this error, but as the project is open source if you would like to contribute trying to fix it (or forking the project) you are welcom.
